name: Mon premier workflow
on: [push]
 
jobs:
 build: 
   runs-on: ubuntu-latest
   steps:
     - run: echo build
 deploy: 
  needs: build
  runs-on: ubuntu-latest
  steps:
    - run: echo deploy in prod
