name: Mon premier workflow
on: [push]

env:
 VAR_1: from workflow
 
jobs:
 say-hello: 
   env:
    VAR_2: from job
   runs-on: ubuntu-latest
   steps:
     - run : echo $ {{ 42 }}
     - run: echo ${{ 'main' == 'top' }}
     - run: echo ${{ contains(github.ref, 'main') }}
