name: Mon premier workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
         titre=$TITRE
         echo Hello World !
        env:
          TITRE: ${{ github.event.head_commit.message }}