name: Mon premier workflow
on: [push]

jobs:
  testdocker:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    container:
      image: node:18
    steps:
      - run: apt update && sudo apt install redis-tools -y
      - run: redis-cli -h localhost -p 6379 ping
